require: rubocop-rspec

Metrics/LineLength:
  Max: 121

Metrics/MethodLength:
  Max: 16

Metrics/ClassLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/ParameterLists:
  Max: 10

Metrics/BlockLength:
  Max: 40

RSpec/ExampleLength:
  Max: 25

Metrics/AbcSize:
  Max: 32

RSpec/MessageSpies:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 13

RSpec/MultipleExpectations:
  Max: 5