require: rubocop-rspec

Metrics/LineLength:
  Max: 121

Metrics/MethodLength:
  Max: 13

Metrics/ClassLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 19

Metrics/CyclomaticComplexity:
  Max: 13